export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL";
export const GET_QUESTION_BY_ID_REQUEST = "GET_QUESTION_BY_ID_REQUEST";
export const GET_QUESTION_BY_ID_SUCCESS = "GET_QUESTION_BY_ID_SUCCESS";
export const GET_QUESTION_BY_ID_FAIL = "GET_QUESTION_BY_ID_FAIL";