import React, {useEffect, useState} from "react";
import Head from "next/head";
import {useDispatch} from "react-redux";
import LoginLayout from "layouts/loginLayout/LoginLayout";
import QuestionCard from "components/questionCard/QuestionCard";
import axiosInstance from "utils/request/axiosInstance";
import {Question} from "utils/types/commonTypes";
import {
    GET_QUESTIONS_FAIL,
    GET_QUESTIONS_REQUEST,
    GET_QUESTIONS_SUCCESS,
} from "store/actionTypes";
import generalText from "i18n/generalText";

export default function Home() {
    const dispatch = useDispatch();
    const [questions, setQuestions] = useState<Question[]>();
    useEffect(() => {
        onGetQuestions();
    }, []);
    const onGetQuestions = () => {
        dispatch({type: GET_QUESTIONS_REQUEST});

        axiosInstance
            .get("/questions")
            .then(res => {
                setQuestions(res.data);
                dispatch({type: GET_QUESTIONS_SUCCESS, payload: res.data});
            })
            .catch(err => {
                dispatch({type: GET_QUESTIONS_FAIL, payload: err});
            });
    };

    return (
        <>
            <Head>
                <title>{generalText.title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1, maximum-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <LoginLayout
                    title={generalText.questionList}
                    updateQuestions={onGetQuestions}
                >
                    {questions?.map(question => (
                        <div key={question.id}>
                            <QuestionCard question={question} />
                        </div>
                    ))}
                </LoginLayout>
            </main>
        </>
    );
}
